# These are the directories where we read the data and store the output
# feel free to change these names
directories :
        Reads: "fastq"
        prinseq: "QC"
        statistics: "statistics"
        read_based_annotations: "ReadAnnotations" 
        atavide_binning: "binning/atavide"
        concoct : "binning/concoct"
        metabat : "binning/metabat"
        ncbi_taxonomy: '/home/edwa0468/ncbi/taxonomy/current/'
        temp_directory: "/scratch/user/edwa0468/tmp"
